### ISSUE TITLE
Weten hoe code uitvoeren bij opstart

### ISSUE THREAD

**Issue by SampersS** [vives-project-xp/DancingLight#117]
**Describe the Issue**
Als we een apparaat willen dat werkt als je het in het stopcontact steekt dan moeten we weten hoe je code uitgevoerd krijgt als je het apparaat opstart, het is dus de bedoeling dat we dit opzoeken.

**Additional context**
nee

**Comment by mSinnaeve04** [comment]
sudo nano /etc/rc.local
python3 /home/pi/myscript.py

**Comment by SampersS** [comment]
getest met rc.local en werkend
