### ISSUE TITLE
een python script maken voor als er geluid is dan toont hij een random effect

### ISSUE THREAD

**Issue by SampersS** [vives-project-xp/DancingLight#89]
**Describe the Issue**
A clear and concise description of what the issue is

**Additional context**

**Comment by SampersS** [comment]
nu kan hij al alle leds aan doen met geluid, maar moet nog systeem verzinnen om effect af te spelen.
source code wordt zodadelijk upgeloadt.

**Comment by mSinnaeve04** [comment]
Niet meer nodig
